// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmmzqzgecacrfxkbmzhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtbXpxemdlY2FjcmZ4a2JtemhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NjkyOTUsImV4cCI6MjA3NDM0NTI5NX0.WQA7Edu9h8wfXHfungvhrussqo7HbE9xD55inRJP_bw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});